# Generated by Django 4.0.4 on 2022-08-15 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('age_start', models.PositiveIntegerField()),
                ('age_stop', models.PositiveIntegerField()),
                ('growth', models.IntegerField()),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_app.income')),
            ],
        ),
    ]
