# Generated by Django 4.0.4 on 2022-08-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomeinstance',
            options={'ordering': ['age_start']},
        ),
    ]
