# Generated by Django 4.0.4 on 2022-08-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0004_alter_incomeinstance_age_start_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incomeinstance',
            unique_together={('income', 'description', 'amount', 'age_start', 'age_stop', 'growth')},
        ),
    ]
