# Generated by Django 4.0.4 on 2022-08-16 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0005_alter_incomeinstance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incomeinstance',
            unique_together={('income', 'description')},
        ),
    ]
