# Generated by Django 4.0.4 on 2022-08-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0006_alter_incomeinstance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeinstance',
            name='age_start',
            field=models.PositiveIntegerField(default=40, null=True),
        ),
        migrations.AlterField(
            model_name='incomeinstance',
            name='age_stop',
            field=models.PositiveIntegerField(default=90, null=True),
        ),
        migrations.AlterField(
            model_name='incomeinstance',
            name='growth',
            field=models.IntegerField(null=True),
        ),
    ]
